apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-benefit-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.git.repo/your-projects.git
    targetRevision: main
    path: devops-infra-helm-argo/helm/umbrella
  destination:
    server: https://kubernetes.default.svc
    namespace: social
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
