apiVersion: v1
kind: ConfigMap
metadata:
  name: connectors-config
  namespace: data
data:
  supabase-jobs.json: |
    {
      "name": "supabase-jobs",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "db.lfjnvafmgwgdzyryjftj.supabase.co",
        "database.port": "5432",
        "database.user": "postgres",
        "database.password": "${file:/etc/connect-secrets/supabase.properties:DB_PASSWORD}",
        "database.dbname": "postgres",
        "database.server.name": "supabase",
        "schema.include.list": "public",
        "table.include.list": "public.jobs,public.job_details",
        "plugin.name": "pgoutput",
        "publication.autocreate.mode": "filtered",
        "slot.name": "debezium_jobs",
        "tombstones.on.delete": "false"
      }
    }
  jdbc-sink-stg-jobs.json: |
    {
      "name": "jdbc-sink-stg-jobs",
      "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "jobmodel.stg_jobs",
        "connection.url": "jdbc:postgresql://db.lfjnvafmgwgdzyryjftj.supabase.co:5432/postgres",
        "connection.user": "postgres",
        "connection.password": "${file:/etc/connect-secrets/supabase.properties:DB_PASSWORD}",
        "auto.create": "false",
        "auto.evolve": "false",
        "insert.mode": "upsert",
        "pk.mode": "record_value",
        "pk.fields": "job_id",
        "table.name.format": "jobmodel.stg_jobs",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter"
      }
    }

