apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-source
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels: { app: debezium-source }
  template:
    metadata:
      labels: { app: debezium-source }
    spec:
      containers:
        - name: connect
          image: debezium/connect:2.6
          ports: [{ containerPort: 8084 }]
          env:
            - { name: BOOTSTRAP_SERVERS, value: crossbring-kafka:9092 }
            - { name: GROUP_ID, value: debezium-cluster }
            - { name: CONFIG_STORAGE_TOPIC, value: _dbz-configs }
            - { name: OFFSET_STORAGE_TOPIC, value: _dbz-offsets }
            - { name: STATUS_STORAGE_TOPIC, value: _dbz-status }
            - { name: KEY_CONVERTER_SCHEMAS_ENABLE, value: "false" }
            - { name: VALUE_CONVERTER_SCHEMAS_ENABLE, value: "false" }
            - { name: ENABLE_DEBEZIUM_SCRIPTING, value: "true" }
          volumeMounts:
            - name: secrets
              mountPath: /etc/connect-secrets
              readOnly: true
          readinessProbe:
            httpGet: { path: /connectors, port: 8084 }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /connectors, port: 8084 }
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests: { cpu: "200m", memory: "512Mi" }
            limits: { cpu: "1", memory: "1Gi" }
      volumes:
        - name: secrets
          secret:
            secretName: supabase-secrets
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-source
  namespace: data
spec:
  selector: { app: debezium-source }
  ports:
    - name: http
      port: 8084
      targetPort: 8084
