apiVersion: v2
name: social-benefit-platform
description: Umbrella chart deploying services and frontend
type: application
version: 0.1.0
dependencies:
  - name: caseservice
    version: 0.1.0
    repository: "file://../charts/caseservice"
  - name: paymentservice
    version: 0.1.0
    repository: "file://../charts/paymentservice"
  - name: eligibility
    version: 0.1.0
    repository: "file://../charts/eligibility"
  - name: citizen-portal
    version: 0.1.0
    repository: "file://../charts/citizen-portal"
