apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossbring-connect
spec:
  destination:
    namespace: data
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/akhilsplendid/crossbring
    targetRevision: HEAD
    path: crossbring-kafka-gitops-blueprints/manifests/connect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
