apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossbring-kafka
spec:
  destination:
    namespace: data
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: "*"
    helm:
      values: |
        replicaCount: 3
        zookeeper.enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

