apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citizen-portal.fullname" . }}
  labels:
    app: {{ include "citizen-portal.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "citizen-portal.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "citizen-portal.name" . }}
    spec:
      containers:
        - name: citizen-portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "citizen-portal.fullname" . }}
spec:
  selector:
    app: {{ include "citizen-portal.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
